# jpa
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# cookie
app.cookie.secure=false
app.cookie.same-site=Lax

# resend
app.mail.from=Group Mission <onboarding@resend.local>

# log
logging.level.root=INFO